name: Selenium Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Install essential commands
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl

      - name: Install Google Chrome
        run: |
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver version 132
        run: |
          # Download ChromeDriver version 132.0.6834.110
          wget https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.110/linux64/chrome-linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Run Selenium tests
        env:
          PATH: /usr/local/bin:/usr/bin:$PATH
        run: |
          google-chrome --version
          chromedriver --version
          python automation_test.py
