name: Selenium Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Test network connectivity
        run: curl -I https://moneygaming.qa.gameaccount.com/

      - name: Install essential commands
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl

      - name: Install Chrome
        run: |
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y

      - name: Download and Install ChromeDriver
        run: |
          wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/132.0.6834.110/linux64/chromedriver-linux64.zip -O chromedriver-linux64.zip
          unzip chromedriver-linux64.zip -d chromedriver-linux64
          sudo mv chromedriver-linux64/chromedriver-linux64/chromedriver /usr/local/bin/
          sudo ln -s /usr/local/bin/chromedriver /usr/bin/chromedriver || true

      - name: Run Selenium tests
        env:
          PATH: /usr/local/bin:/usr/bin:$PATH
        run: |
          google-chrome --version
          chromedriver --version
          python automation_test.py
